# Generated by Django 5.0.3 on 2024-04-07 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, default='static/images/no_image.png', null=True, upload_to='cars_image')),
                ('year', models.IntegerField(default=2020)),
                ('gearbox', models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='categories.category')),
            ],
        ),
    ]
