# Generated by Django 5.0.3 on 2024-03-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Audi', 'Audi')], max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='cars_image')),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('SUV', 'SUV'), ('Compact', 'Compact'), ('EV', 'EV')], max_length=20)),
                ('gearbox', models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], max_length=20)),
            ],
        ),
    ]
