# Generated by Django 5.0.3 on 2024-03-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Audi', 'Audi')], default='BMW', max_length=20),
        ),
        migrations.AlterField(
            model_name='cars',
            name='category',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Compact', 'Compact'), ('EV', 'EV')], default='SUV', max_length=20),
        ),
        migrations.AlterField(
            model_name='cars',
            name='gearbox',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
