# Generated by Django 5.0.3 on 2024-03-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_brand_alter_cars_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.IntegerField(default=1200),
            preserve_default=False,
        ),
    ]
