# Generated by Django 5.0.3 on 2024-03-25 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_cars_slug'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cars', to='categories.category'),
        ),
    ]
