# Generated by Django 5.0.3 on 2024-03-27 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_cars_category'),
        ('categories', '0005_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='categories.category'),
        ),
    ]
