# Generated by Django 5.0.3 on 2024-03-31 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_rentifyprofile_user'),
        ('cars', '0012_alter_cars_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('bill_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='booking_profile', to='accounts.rentifyprofile')),
                ('booked_car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='booking_car', to='cars.cars')),
            ],
        ),
    ]
