# Generated by Django 5.0.3 on 2024-04-01 12:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 18), null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 18), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bill_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='booking_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
