# Generated by Django 5.0.3 on 2024-04-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_end_date_alter_booking_start_date'),
        ('cars', '0012_alter_cars_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_car', to='cars.cars'),
        ),
    ]
