# Generated by Django 5.0.3 on 2024-03-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rentifyprofile_city_rentifyprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentifyprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='rentifyprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='rentifyprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='rentifyprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='rentifyprofile',
            name='profile_picture',
        ),
    ]
