# Generated by Django 5.0.3 on 2024-03-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_rentifyprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentifyprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
